# Generated by Django 5.1 on 2024-10-06 04:12

import account.models
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('far_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=30, prefix='far', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=account.models.user_directory_path)),
                ('decription', models.TextField(blank=True, null=True)),
                ('address', models.CharField(default='India', max_length=100)),
                ('contact', models.CharField(default='+91XXX XXX XXXX', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Farmers',
            },
        ),
    ]
