# Generated by Django 5.1 on 2024-10-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
