# Generated by Django 5.1 on 2024-11-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_delete_profile'),
        ('shop', '0005_remove_order_billing_address_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
