# Generated by Django 3.2.7 on 2024-11-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_delivery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('subject', models.TextField(max_length=255)),
                ('message', models.TextField(max_length=555)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
