# Generated by Django 3.2.7 on 2024-11-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_order_id'),
        ('shop', '0008_contactus'),
    ]

    operations = [
    ]
