# Generated by Django 5.1 on 2024-10-06 04:19

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=30, prefix='var', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price_per_kg', models.IntegerField(max_length=5)),
                ('image', models.ImageField(upload_to='Variety')),
            ],
            options={
                'verbose_name_plural': 'Varieties',
            },
        ),
    ]
