# Generated by Django 5.1 on 2024-10-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0003_auto_20241007_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descripttion', models.TextField()),
                ('causes', models.TextField()),
                ('image', models.ImageField(upload_to='Diseases')),
            ],
            options={
                'verbose_name_plural': 'Diseases',
            },
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(upload_to='Cart Order Items'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='Products'),
        ),
    ]
