# Generated by Django 5.1 on 2024-10-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0004_disease_alter_cartorderitems_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='descripttion',
            new_name='description',
        ),
    ]
