# Generated by Django 5.1 on 2024-10-07 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0005_rename_descripttion_disease_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_image', to='tomatoes.product'),
        ),
    ]
