# Generated by Django 5.1 on 2024-10-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0006_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variety',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
