# Generated by Django 5.1 on 2024-10-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0008_product_life_product_mfg_date_product_stock_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='tomatoes.product'),
        ),
    ]
