# Generated by Django 3.2.7 on 2024-11-06 15:13

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0010_alter_product_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=30, prefix='var', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Vegetables')),
            ],
            options={
                'verbose_name_plural': 'Vegetables',
            },
        ),
        migrations.DeleteModel(
            name='Variety',
        ),
    ]
