# Generated by Django 5.1 on 2024-11-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0011_auto_20241106_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variety',
        ),
    ]
