# Generated by Django 5.1 on 2024-11-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0012_remove_product_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=99999999999999),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
